Repository webpack-contrib/schema-utils, pull requests merged in 2018-08, with the labels that each got.

#26 fix(package): remove unnecessary `webpack` dependency (`dev/peerDependencies`)
  package-lock.json
  package.json
Labels: pr_action: Rebase, priority: 3 (required), semver: Patch, status: Pending, type: Bug

#28 fix(package): remove lockfile
  .npmrc
  package-lock.json
Labels: semver: Patch, severity: 1 (security), status: Approved, type: Bug

#32 fix(src): `node >= v4.0.0` support
  .travis.yml
  package.json
  src/ValidationError.js
  src/index.js
  src/validateOptions.js
  test/index.test.js
Labels: pr_action: Review, priority: 2 (urgent), semver: Patch, severity: 2 (regression), type: Bug

#33 feat(src): add support for custom error messages
  README.md
  package.json
  src/ValidationError.js
  src/validateOptions.js
  test/__snapshots__/index.test.js.snap
  test/fixtures/errors/schema.json
  test/index.test.js
Labels: pr_action: Merge ready, semver: Minor, status: Approved, type: Feature
